// ═══════════════════════════════════════════════════════════════════
// POPULAR QUERIES — scraped every 2 days by cron
// Organized by category for maximum catalog coverage
// ═══════════════════════════════════════════════════════════════════

module.exports = [
  // ─── HOLIDAY BARBIES (by year) ───
  'holiday barbie 2025',
  'holiday barbie 2024',
  'holiday barbie 2023',
  'holiday barbie 2022',
  'holiday barbie 2021',
  'holiday barbie 2020',
  'holiday barbie 2019',
  'holiday barbie 2018',
  'holiday barbie 2017',
  'holiday barbie 2016',
  'holiday barbie 2015',
  'holiday barbie 2014',
  'holiday barbie 2013',
  'holiday barbie 2012',
  'holiday barbie 2010',
  'holiday barbie 2005',
  'holiday barbie 2000',
  'holiday barbie 1998',
  'holiday barbie 1995',
  'holiday barbie 1990',
  'holiday barbie 1988',

  // ─── DIA DE MUERTOS ───
  'dia de muertos barbie 2025',
  'dia de muertos barbie 2024',
  'dia de muertos barbie 2023',
  'dia de muertos barbie 2022',
  'dia de muertos barbie 2021',
  'dia de muertos barbie 2020',
  'dia de muertos ken',

  // ─── CELEBRITY / POP CULTURE ───
  'stevie nicks barbie',
  'clueless barbie cher',
  'barbie movie margot robbie',
  'audrey hepburn barbie',
  'marilyn monroe barbie',
  'elvis presley barbie',
  'david bowie barbie',
  'billie eilish barbie',
  'cher bob mackie barbie',
  'elton john barbie',
  'tina turner barbie',
  'whitney houston barbie',
  'jennifer lopez barbie',
  'lucille ball barbie',
  'grace kelly barbie',
  'farrah fawcett barbie',
  'cyndi lauper barbie',
  'queen elizabeth barbie',
  'laverne cox barbie',
  'kylie minogue barbie',

  // ─── BOB MACKIE ───
  'bob mackie barbie gold',
  'bob mackie barbie platinum',
  'bob mackie barbie neptune',
  'bob mackie barbie empress bride',
  'bob mackie barbie masquerade',
  'bob mackie barbie goddess sun',
  'bob mackie barbie moon goddess',

  // ─── SILKSTONE / BFMC ───
  'silkstone barbie lingerie',
  'barbie fashion model collection',
  'silkstone barbie cocktail dress',
  'bfmc barbie doll',
  'silkstone barbie nurse',

  // ─── INSPIRING WOMEN ───
  'barbie inspiring women',
  'barbie amelia earhart',
  'barbie katherine johnson',
  'barbie maya angelou',
  'barbie ella fitzgerald',
  'barbie florence nightingale',
  'barbie rosa parks',
  'barbie frida kahlo',
  'barbie ida b wells',
  'barbie helen keller',
  'barbie billie jean king',
  'barbie bessie coleman',

  // ─── DOLLS OF THE WORLD ───
  'barbie dolls of the world',
  'barbie dolls world japan',
  'barbie dolls world china',
  'barbie dolls world india',
  'barbie dolls world mexico',
  'barbie dolls world ireland',
  'barbie dolls world spain',
  'barbie dolls world italy',
  'barbie dolls world france',
  'barbie dolls world brazil',
  'barbie dolls world australia',
  'barbie dolls world native american',

  // ─── SIGNATURE / COLLECTOR LABELS ───
  'barbie signature collector',
  'barbie gold label',
  'barbie platinum label',
  'barbie pink label',
  'barbie black label',
  'barbie gala collection',
  'barbie galas best silkstone',
  'barbie birthday wishes',
  'barbie ballet wishes',
  'barbie convention exclusive',

  // ─── DESIGNER COLLABS ───
  'barbie reem acra bride',
  'barbie oscar de la renta',
  'barbie vera wang bride',
  'barbie byron lars treasures of africa',
  'barbie christian louboutin',
  'barbie karl lagerfeld',
  'barbie moschino',
  'barbie coach',
  'barbie balmain',
  'barbie robert best silkstone',

  // ─── MOVIE / TV COLLABS ───
  'barbie wizard of oz',
  'barbie star wars',
  'barbie wonder woman',
  'barbie grease sandy',
  'barbie gone with the wind',
  'barbie jurassic world',
  'barbie harley quinn',
  'barbie poison ivy',
  'barbie tomb raider',
  'barbie i love lucy',
  'barbie alice in wonderland',

  // ─── GREAT ERAS COLLECTION (Barbiepedia) ───
  'barbie great eras collection',
  'barbie great eras egyptian queen',
  'barbie great eras gibson girl',
  'barbie great eras flapper',
  'barbie great eras grecian goddess',
  'barbie great eras medieval lady',
  'barbie great eras southern belle',

  // ─── HOLLYWOOD LEGENDS (Barbiepedia) ───
  'barbie hollywood legends collection',
  'barbie hollywood legends scarlett ohara',
  'barbie hollywood legends dorothy wizard oz',
  'barbie hollywood legends marilyn gentleman',
  'barbie hollywood legends eliza doolittle',

  // ─── LICENSED BRAND COLLABS (Barbiepedia) ───
  'barbie coca cola collector',
  'barbie coca cola soda fountain',
  'barbie harley davidson collector',
  'barbie hard rock cafe collector',
  'barbie nascar collector',

  // ─── ENCHANTED / NATURE SERIES (Barbiepedia) ───
  'barbie enchanted seasons collection',
  'barbie enchanted seasons snow princess',
  'barbie enchanted seasons autumn glory',
  'barbie birds of beauty collection',
  'barbie birds of beauty peacock',
  'barbie fairy of the forest',
  'barbie angels of music',

  // ─── JEWEL / CELESTIAL / ZODIAC (Barbiepedia) ───
  'barbie jewel essence collection',
  'barbie celestial collection',
  'barbie zodiac collection',
  'barbie birthstone beauties',

  // ─── ANNIVERSARY EDITIONS (Barbiepedia) ───
  'barbie 35th anniversary',
  'barbie 40th anniversary',
  'barbie 50th anniversary',
  'barbie 60th anniversary',
  'barbie 65th anniversary',

  // ─── BARBIESTYLE (Barbiepedia) ───
  'barbie barbiestyle doll',
  'barbie barbiestyle fashion',

  // ─── ADDITIONAL BARBIEPEDIA COLLECTIONS ───
  'barbie andy warhol collector',
  'barbie elizabeth taylor collection',
  'barbie portrait collection',
  'barbie women of royalty',
  'barbie legends of ireland',
  'barbie pin up girls collection',
  'barbie grand entrance collection',
  'barbie ballroom beauties collection',
  'barbie winter princess collection',
  'barbie city seasons collection',
  'barbie royal jewels collection',
  'barbie diva collection',
  'barbie jazz baby collection',
  'barbie native spirit collection',
  'barbie lounge kitties collection',
  'barbie faraway forest collection',
  'barbie the blonds collection',
  'barbie pop life collection',
  'barbie keepsake treasures collection',
  'barbie timeless sentiments collection',
  'barbie together forever collection',
  'barbie bridal collection',
  'barbie princess series',
  'barbie harlem theater collection',
  'barbie museum collection',
  'barbie black and white collection',
  'barbie style set collection',
  'barbie modern circle collection',
  'barbie blonde ambition collection',
  'barbie superstar forever collection',
  'barbie fashion savvy collection',
  'barbie great villains collection',
  'barbie dream seasons collection',
  'barbie dancing with the stars',
  'barbie enchanted world fairy',
  'barbie barbie loves bond',
  'barbie society style collection',
  'barbie collector request collection',
  'barbie american stories collection',
  'barbie loves pop culture',
  'barbie classic ballet series',
  'barbie spiegel exclusive',
  'barbie hallmark exclusive',
  'barbie ferrari collection',
  'barbie hollywood movie star collection',
  'barbie designer spotlight collection',
  'barbie global glamour collection',
  'barbie classical goddess collection',
  'barbie essence of nature collection',

  // ─── VINTAGE REPRODUCTIONS ───
  'barbie 1959 reproduction',
  'vintage barbie ponytail',
  'vintage barbie bubble cut',
  'barbie twist n turn',
  'malibu barbie reproduction',
  'superstar barbie reproduction',
  'barbie and the rockers reproduction',
  'totally hair barbie reproduction',

  // ─── BARBIE LOOKS ───
  'barbie looks doll',
  'barbie looks made to move',
  'barbie looks ken',

  // ─── BARBIE BASICS ───
  'barbie basics model',
  'barbie basics collection',
  'barbie basics black dress',

  // ─── FASHIONISTAS ───
  'barbie fashionistas',
  'barbie fashionistas wheelchair',
  'barbie fashionistas prosthetic',
  'barbie fashionistas curvy',
  'barbie fashionistas ken',

  // ─── CUTIE REVEAL / COLOR REVEAL ───
  'barbie cutie reveal',
  'barbie color reveal',
  'barbie color reveal mermaid',
  'barbie pop reveal',

  // ─── CAREER DOLLS ───
  'barbie career',
  'barbie doctor',
  'barbie astronaut',
  'barbie president',
  'barbie pilot',
  'barbie veterinarian',
  'barbie firefighter',
  'barbie engineer',
  'barbie teacher',

  // ─── PLAYSETS & VEHICLES ───
  'barbie dreamhouse',
  'barbie dreamcamper',
  'barbie airplane',
  'barbie corvette',
  'barbie pool party playset',
  'barbie ice cream shop',
  'barbie pizza oven',
  'barbie pet boutique',

  // ─── EXTRA / MISC ───
  'barbie extra doll',
  'barbie extra fly',
  'barbie extra minis',
  'barbie chelsea',
  'barbie skipper',
  'barbie dreamtopia mermaid',
  'barbie princess',
  'barbie fairy',
  'barbie and ken wedding',
];
